### ISSUE TITLE
json parameters file

### ISSUE THREAD

**Issue by sangoncalves** [shanice-l/st-cubsim#55]
Hi, congratz on fantastic work! I´m studying your paper and going to use it as a baseline comparison. Do you mind sharing the json parameter file (params.json) so I have your work as it is on the paper for comparison?

**Comment by shanice-l** [comment]
Sry. The work was done at the IVG lab, but I've been left there for a long time.
So I can't fetch the JSON file either.

But I think you can use the JSON file of HCN-pytorch. The experimental results will be roughly the same.

**Comment by sangoncalves** [comment]
I see, thanks for the reply! I will try to use it as suggested.
